### ISSUE TITLE
I need help to run this for the 1st time

### ISSUE THREAD

**Issue by leoheck** [Gasman2014/KiCad-Diff#11]
Hi, do you know what is going on here? 

My pcb is not the root of the repo, can this be the issue here?

The Plot folder was created with the folders/files
```
➜ ls *
3454d1:
yardbird.kicad_pcb

e80aa7:
yardbird.kicad_pcb
```

```
➜ /home/lheck/Dropbox/kicad-plugins/KiCad-Diff/kidiff_linux.py -h
Commit1 e80aa7a 	 Update step model for the 0.3.2 version.
Commit2 3454d1a 	 Fix links.
cd /home/lheck/Dropbox/deepx/YARDBIRD/board/yardbird-0.3.2/pcb && /usr/bin/git show -s --format="%ci" e80aa7 cd /home/lheck/Dropbox/deepx/YARDBIRD/board/yardbird-0.3.2/pcb && /usr/bin/git show -s --format="%ci" 3454d1
2020-05-25 17:09:56 2020-04-30 15:44:47
Generating .svg files
Traceback (most recent call last):
  File "/home/lheck/Dropbox/kicad-plugins/KiCad-Diff/kidiff_linux.py", line 1594, in <module>
    svgDir1, svgDir2, boardDims1, boardDims2 = makeSVG(d1, d2, prjctName, prjctPath)
  File "/home/lheck/Dropbox/kicad-plugins/KiCad-Diff/kidiff_linux.py", line 1184, in makeSVG
    return (d1, d2, plotDims1[0], plotDims2[0])
IndexError: list index out of range
```

**Comment by leoheck** [comment]
Running the gui I got this
I fixed it by replacing the `_escape_string(gitRoot)` with `gitRoot` now
```
➜ /home/lheck/Dropbox/kicad-plugins/KiCad-Diff/kidiff_gui.py
Fossil 
Git 
SVN 
Commit1 e80aa7a 	 Update step model for the 0.3.2 version.
Commit2 43f6d0f 	 More space for connector wires/strain relief.
cd /home/lheck/Dropbox/deepx/YARDBIRD/board/yardbird-0.3.2/pcb && /usr/bin/git diff --name-only e80aa7 43f6d0 | /usr/bin/grep *.kicad_pcb
Traceback (most recent call last):
  File "/home/lheck/Dropbox/kicad-plugins/KiCad-Diff/kidiff_gui.py", line 1580, in <module>
    times = getGitDiff(d1, d2, prjctName, prjctPath)
  File "/home/lheck/Dropbox/kicad-plugins/KiCad-Diff/kidiff_gui.py", line 727, in getGitDiff
    gitPath = getGitPath(prjctName, prjctPath)
  File "/home/lheck/Dropbox/kicad-plugins/KiCad-Diff/kidiff_gui.py", line 676, in getGitPath
    gitPathCmd = 'cd ' + _escape_string(gitRoot) + ' && ' + gitProg + ' ls-tree -r --name-only HEAD | ' + grepProg + ' -m 1 ' + prjctName
NameError: name '_escape_string' is not defined
```

**Comment by leoheck** [comment]
I found that some commands are not good. At least the output in the console.
Some `cd` commands do not have a comma before. So these commands look strange to me



cd /home/lheck/Dropbox/deepx/YARDBIRD/board/yardbird-0.3.2/pcb && \
	/usr/bin/git diff --name-only e80aa7 3454d1 | /usr/bin/grep *.kicad_pcb

cd /home/lheck/Dropbox/deepx/YARDBIRD/board/yardbird-0.3.2/pcb && \
	/usr/bin/git show e80aa7: > /home/lheck/Dropbox/deepx/YARDBIRD/board/yardbird-0.3.2/pcb/Plots/e80aa7/yardbird.kicad_pcb cd /home/lheck/Dropbox/deepx/YARDBIRD/board/yardbird-0.3.2/pcb && /usr/bin/git show 3454d1: > /home/lheck/Dropbox/deepx/YARDBIRD/board/yardbird-0.3.2/pcb/Plots/3454d1/yardbird.kicad_pcb

cd /home/lheck/Dropbox/deepx/YARDBIRD/board/yardbird-0.3.2/pcb && \
	/usr/bin/git show -s --format="%ci" e80aa7 cd /home/lheck/Dropbox/deepx/YARDBIRD/board/yardbird-0.3.2/pcb && /usr/bin/git show -s --format="%ci" 3454d1

**Comment by sunwukonga** [comment]
> Running the gui I got this
> I fixed it by replacing the `_escape_string(gitRoot)` with `gitRoot` now
> 
> ```
> ➜ /home/lheck/Dropbox/kicad-plugins/KiCad-Diff/kidiff_gui.py
> Fossil 
> Git 
> SVN 
> Commit1 e80aa7a 	 Update step model for the 0.3.2 version.
> Commit2 43f6d0f 	 More space for connector wires/strain relief.
> cd /home/lheck/Dropbox/deepx/YARDBIRD/board/yardbird-0.3.2/pcb && /usr/bin/git diff --name-only e80aa7 43f6d0 | /usr/bin/grep *.kicad_pcb
> Traceback (most recent call last):
>   File "/home/lheck/Dropbox/kicad-plugins/KiCad-Diff/kidiff_gui.py", line 1580, in <module>
>     times = getGitDiff(d1, d2, prjctName, prjctPath)
>   File "/home/lheck/Dropbox/kicad-plugins/KiCad-Diff/kidiff_gui.py", line 727, in getGitDiff
>     gitPath = getGitPath(prjctName, prjctPath)
>   File "/home/lheck/Dropbox/kicad-plugins/KiCad-Diff/kidiff_gui.py", line 676, in getGitPath
>     gitPathCmd = 'cd ' + _escape_string(gitRoot) + ' && ' + gitProg + ' ls-tree -r --name-only HEAD | ' + grepProg + ' -m 1 ' + prjctName
> NameError: name '_escape_string' is not defined
> ```

Can you try removing line 39:
```
val = val.replace( u'\\', u'\\\\' )
```

`_escape_string` is only there to escape spaces in file paths and names.

**Comment by sunwukonga** [comment]
> I found that some commands are not good. At least the output in the console.
> Some cd commands do not have a comma before. So these commands look strange to me

What is not good, exactly? Why would a `cd` command need a `,` in front of it?

**Comment by leoheck** [comment]
> What is not good, exactly? Why would a cd command need a , in front of it?

I don't know actually.

I am running your _gui.py 
I put the plotPCB.py to the path where your readme said to.

But the diff is not being generated. Do you have any ideia what should I do?

**Comment by leoheck** [comment]
> First, what OS are you using?
Didn't see this.
Ubuntu 20.04

**Comment by leoheck** [comment]
The _linux.py command line to generate images work.
The _gui works (or almost work) 
The Plot folder is generated
![image](https://user-images.githubusercontent.com/1277920/82975706-9ec69c00-9fb3-11ea-8664-752034ce60a7.png)

**Comment by leoheck** [comment]
The content is this
![image](https://user-images.githubusercontent.com/1277920/82975765-bbfb6a80-9fb3-11ea-9a5e-16c603ea1714.png)

**Comment by sunwukonga** [comment]
You're using `kidiff_gui.py` OR `kidiff_linux.py` they are independent. If using `kidiff_linux.py` that's all you need.

**Comment by leoheck** [comment]
I am trying both, actually. I would like to make the diff between git versions. The kidiff_linux.py generates only a folder with a bunch of svg's I didn't pass any commit to compare. Can I pass the git commit to that command? I didn't find it on REAMDE.

**Comment by leoheck** [comment]
Do you have ane usage example? Maybe this is my problem. Maybe I am not using it right.

**Comment by sunwukonga** [comment]
Can you post your repo? I can have a look from my end. I'll be able to diagnose more quickly.

**Comment by sunwukonga** [comment]
The kidiff_gui.py will NOT be able to handle `.kicad_pcb` files that are not in the git root.

**Comment by leoheck** [comment]
Yeah, that is what I was thinking about. Any reason for that? Or it is just how it was done now?

**Comment by leoheck** [comment]
I am sorry, I can't share the repo.
But this is the layout of the folders
![image](https://user-images.githubusercontent.com/1277920/82976126-a9cdfc00-9fb4-11ea-9ee7-36b4cdd77252.png)

**Comment by sunwukonga** [comment]
Just run `kidiff_linux.py` from anywhere is the usage. No need for switches or paths.

**Comment by leoheck** [comment]
Yeah, I am doing this. It generates images of the board, right?

**Comment by leoheck** [comment]
So, if this can't handle the board in a folder, I can still generate images with the kidiff_linux.py then use the imagemagic to compare them.

**Comment by sunwukonga** [comment]
In the commit hash subdirectories of the `plots` directory, there should be many `svg` files generated. Do you see this?

**Comment by leoheck** [comment]
If I can add here, I would like to suggest.

- Handling boards on different folders.
- Improving the command line.

I would suggest 

kidiff_gui.py

**Comment by sunwukonga** [comment]
Are you then viewing the generated HTML at `http://127.0.0.1:9092/web/index.html`

**Comment by leoheck** [comment]
If I can add here, I would like to suggest.

- Handling boards on different folders.
- Improving the command line.

I would suggest at least be able to pass the pcb from the command line. Then figure it out the main scm folder, and then the board folder inside the repo. Also if the user can pass the commit from the command line would be greate.


```
kidiff_gui.py <kicad_pcb> [-a commit] [-b commit]
```

**Comment by leoheck** [comment]
> Are you then viewing the generated HTML at http://127.0.0.1:9092/web/index.html

 I am not even closer since my repo does not have the board on the root.

**Comment by sunwukonga** [comment]
Thanks. That `_escape_string` should NOT be in `kidiff_gui.py` at all.

**Comment by sunwukonga** [comment]
`kidiff_linux.py` can handle `kicad_pcb` files that aren't in root. There must be another cause.

**Comment by leoheck** [comment]
Look this (using the 

```
Commit1 e80aa7a 	 Update step model for the 0.3.2 version.
Commit2 3454d1a 	 Fix links.
cd /home/lheck/Dropbox/deepx/YARDBIRD/board/yardbird-0.3.2/pcb && /usr/bin/git show -s --format="%ci" e80aa7 cd /home/lheck/Dropbox/deepx/YARDBIRD/board/yardbird-0.3.2/pcb && /usr/bin/git show -s --format="%ci" 3454d1
2020-05-25 17:09:56 2020-04-30 15:44:47
Generating .svg files
Traceback (most recent call last):
  File "/home/lheck/Dropbox/kicad-plugins/KiCad-Diff/kidiff_linux.py", line 1594, in <module>
    svgDir1, svgDir2, boardDims1, boardDims2 = makeSVG(d1, d2, prjctName, prjctPath)
  File "/home/lheck/Dropbox/kicad-plugins/KiCad-Diff/kidiff_linux.py", line 1184, in makeSVG
    return (d1, d2, plotDims1[0], plotDims2[0])
IndexError: list index out of range
```

This is the 3rd line on this log. I am braking the lines afer the && and adding a \ to be able to execute on the command line.
Look the cd commands, they are not good. Do you agree?

```
cd /home/lheck/Dropbox/deepx/YARDBIRD/board/yardbird-0.3.2/pcb && \
	/usr/bin/git show -s --format="%ci" e80aa7 cd /home/lheck/Dropbox/deepx/YARDBIRD/board/yardbird-0.3.2/pcb && \
	/usr/bin/git show -s --format="%ci" 3454d1

```

**Comment by sunwukonga** [comment]
That `cd` command seems fine to me. I see your confusion though. You can ignore this. This is just a console print of the commands one after the other. It is NOT executing them there. 

The error is actually from a previous error. I.e. your `plotDims1` is not being generated properly.

**Comment by leoheck** [comment]
Yes, true. Any idea on how I debug or how I can give you more info?

**Comment by leoheck** [comment]
Just one FYI, here in ubuntu 20.04 I had to change this (kidiff_gui.py)
```
-    gui = tk.Tk(':0.0', SCMS)
+    gui = tk.Tk(':1.0', SCMS)
```

**Comment by sunwukonga** [comment]
To troubleshoot, I would suggest adding the following line at line 1159:
```
print(plot1Cmd,plot2Cmd)
```

Fair warning, as with the other console output, this is two commands printed together. So you'll have to be aware of that when you read it.

**Comment by leoheck** [comment]
Sure! 

The lines changed a little bit since my last changes have the original commented

Is it something like this, right?
![image](https://user-images.githubusercontent.com/1277920/82977347-f49d4300-9fb7-11ea-9213-87334cb4a22c.png)

**Comment by leoheck** [comment]
```
➜ /home/lheck/Dropbox/kicad-plugins/KiCad-Diff/kidiff_linux.py
Commit1 e80aa7a 	 Update step model for the 0.3.2 version.
Commit2 3454d1a 	 Fix links.
cd /home/lheck/Dropbox/deepx/YARDBIRD/board/yardbird-0.3.2/pcb && /usr/bin/git show -s --format="%ci" e80aa7 cd /home/lheck/Dropbox/deepx/YARDBIRD/board/yardbird-0.3.2/pcb && /usr/bin/git show -s --format="%ci" 3454d1
2020-05-25 17:09:56 2020-04-30 15:44:47
Generating .svg files
Traceback (most recent call last):
  File "/home/lheck/Dropbox/kicad-plugins/KiCad-Diff/kidiff_linux.py", line 1594, in <module>
    svgDir1, svgDir2, boardDims1, boardDims2 = makeSVG(d1, d2, prjctName, prjctPath)
  File "/home/lheck/Dropbox/kicad-plugins/KiCad-Diff/kidiff_linux.py", line 1184, in makeSVG
    return (d1, d2, plotDims1[0], plotDims2[0])
IndexError: list index out of range

```

**Comment by leoheck** [comment]
I can't see differences.. can you?

**Comment by leoheck** [comment]
Wrong file? I changed it in the kidiff_gui =/

**Comment by leoheck** [comment]
Even the lines match now haha.

```
✦ ➜ Commit1 e80aa7a 	 Update step model for the 0.3.2 version.
Commit2 3454d1a 	 Fix links.
cd /home/lheck/Dropbox/deepx/YARDBIRD/board/yardbird-0.3.2/pcb && /usr/bin/git show -s --format="%ci" e80aa7 cd /home/lheck/Dropbox/deepx/YARDBIRD/board/yardbird-0.3.2/pcb && /usr/bin/git show -s --format="%ci" 3454d1
2020-05-25 17:09:56 2020-04-30 15:44:47
Generating .svg files
/home/spendless/sandpit/KiCad-Diff/plotPCB.py /home/lheck/Dropbox/deepx/YARDBIRD/board/yardbird-0.3.2/pcb/plots/e80aa7/yardbird.kicad_pcb /home/lheck/Dropbox/deepx/YARDBIRD/board/yardbird-0.3.2/pcb/plots/e80aa7 /home/spendless/sandpit/KiCad-Diff/plotPCB.py /home/lheck/Dropbox/deepx/YARDBIRD/board/yardbird-0.3.2/pcb/plots/3454d1/yardbird.kicad_pcb /home/lheck/Dropbox/deepx/YARDBIRD/board/yardbird-0.3.2/pcb/plots/3454d1
Traceback (most recent call last):
  File "/home/lheck/Dropbox/kicad-plugins/KiCad-Diff/kidiff_linux.py", line 1596, in <module>
    svgDir1, svgDir2, boardDims1, boardDims2 = makeSVG(d1, d2, prjctName, prjctPath)
  File "/home/lheck/Dropbox/kicad-plugins/KiCad-Diff/kidiff_linux.py", line 1186, in makeSVG
    return (d1, d2, plotDims1[0], plotDims2[0])
IndexError: list index out of range

[1]  + 256221 exit 1     /home/lheck/Dropbox/kicad-plugins/KiCad-Diff/kidiff_linux.py
```

**Comment by sunwukonga** [comment]
They look OK. The problem must lie in `plotPCB.py`.

**Comment by leoheck** [comment]
I don't believe that.
because when I look into them, the content is not the right thing
let me check.

**Comment by leoheck** [comment]
Yeah, the files are good. They also work in pcbnew

**Comment by leoheck** [comment]
This works too
```
➜ plotPCB.py yardbird.kicad_pcb lala
127199943 62265000 149142914 61785001
```

**Comment by sunwukonga** [comment]
But the `svg` files were not generated to the `plots` directory?

**Comment by leoheck** [comment]
Not, the command above was made to use the `lala` folder instead

**Comment by leoheck** [comment]
The output is good, what should this do?

/home/spendless/sandpit/KiCad-Diff/plotPCB.py
![image](https://user-images.githubusercontent.com/1277920/82978090-11d31100-9fba-11ea-9a99-18fa5c4608f9.png)

**Comment by leoheck** [comment]
Yeah, it is working, right?

![image](https://user-images.githubusercontent.com/1277920/82978124-27e0d180-9fba-11ea-87aa-09e1420f84b9.png)

**Comment by sunwukonga** [comment]
That looks good.

**Comment by leoheck** [comment]
Only one folder has icons, is it right?

**Comment by sunwukonga** [comment]
You only ran one side, not the other side. You'd have to copy paste the other command to get those as well.

**Comment by leoheck** [comment]
ah, ok
let me try here

**Comment by leoheck** [comment]
Cool, it worked

**Comment by leoheck** [comment]
> That's puzzling. I don't see why those commands would work directly, but not when called by Popen.
Indeed!

**Comment by leoheck** [comment]
let me learn how to use Popen to test here

**Comment by sunwukonga** [comment]
I'm using Python 3.8.2; what version do you have?

**Comment by leoheck** [comment]
Just to give more info
➜ python3 --version 
Python 3.8.2

**Comment by leoheck** [comment]
ah hehe, same time

**Comment by leoheck** [comment]
Do you use stderr? We should print it?

**Comment by sunwukonga** [comment]
It wasn't used, but you can.
Add:
```
print("STDERR" + stderr.decode('utf-8'))
```

**Comment by leoheck** [comment]
This is the problem

yardbird-0.3.2/pcb on  yardbird-0.3-chamfer [?] 

```
✦ ➜ echo /home/lheck/Dropbox/deepx/YARDBIRD/board/yardbird-0.3.2/pcb/yardbird.kicad_pcbCommit1 e80aa7a 	 Update step model for the 0.3.2 version.
Commit2 3454d1a 	 Fix links.
cd /home/lheck/Dropbox/deepx/YARDBIRD/board/yardbird-0.3.2/pcb && /usr/bin/git show -s --format="%ci" e80aa7 cd /home/lheck/Dropbox/deepx/YARDBIRD/board/yardbird-0.3.2/pcb && /usr/bin/git show -s --format="%ci" 3454d1
2020-05-25 17:09:56 2020-04-30 15:44:47
Generating .svg files
>>>  /home/spendless/sandpit/KiCad-Diff/plotPCB.py /home/lheck/Dropbox/deepx/YARDBIRD/board/yardbird-0.3.2/pcb/plots/e80aa7/yardbird.kicad_pcb /home/lheck/Dropbox/deepx/YARDBIRD/board/yardbird-0.3.2/pcb/plots/e80aa7

>>>  /home/spendless/sandpit/KiCad-Diff/plotPCB.py /home/lheck/Dropbox/deepx/YARDBIRD/board/yardbird-0.3.2/pcb/plots/3454d1/yardbird.kicad_pcb /home/lheck/Dropbox/deepx/YARDBIRD/board/yardbird-0.3.2/pcb/plots/3454d1

out>  b''

err>  b'/bin/sh: 1: /home/spendless/sandpit/KiCad-Diff/plotPCB.py: not found\n'

>  []


out>  b''

err>  b'/bin/sh: 1: /home/spendless/sandpit/KiCad-Diff/plotPCB.py: not found\n'

>  []

Traceback (most recent call last):
  File "/home/lheck/Dropbox/kicad-plugins/KiCad-Diff/kidiff_linux.py", line 1613, in <module>
    svgDir1, svgDir2, boardDims1, boardDims2 = makeSVG(d1, d2, prjctName, prjctPath)
  File "/home/lheck/Dropbox/kicad-plugins/KiCad-Diff/kidiff_linux.py", line 1203, in makeSVG
    return (d1, d2, plotDims1[0], plotDims2[0])
IndexError: list index out of range

[1]  + 265928 exit 1     /home/lheck/Dropbox/kicad-plugins/KiCad-Diff/kidiff_linux.py

```

**Comment by leoheck** [comment]
:)
plotProg = '/home/spendless/sandpit/KiCad-Diff/plotPCB.py'

**Comment by leoheck** [comment]
And there are the right one! Good Job. Let me try
plotProg = '/usr/local/bin/plotPCB.py'

**Comment by sunwukonga** [comment]
Yeah, that's a configurable. Our bad though. It should definitely print the error to show the issue.

**Comment by leoheck** [comment]
AWEEEESSOME! hehe

**Comment by leoheck** [comment]
yardbird-B_Paste.svg
yardbird-Edge_Cuts.svg
yardbird-In1_Cu.svg
yardbird-F_Paste.svg
yardbird-Eco2_User.svg
yardbird-F_Adhes.svg
yardbird-Margin.svg
yardbird-F_CrtYd.svg
yardbird-F_SilkS.svg
yardbird-F_Fab.svg
yardbird-B_Cu.svg
yardbird-Dwgs_User.svg
yardbird-F_Cu.svg
yardbird-In2_Cu.svg
yardbird-B_Fab.svg
yardbird-B_CrtYd.svg
yardbird-Eco1_User.svg
yardbird-Cmts_User.svg
yardbird-B_SilkS.svg
yardbird-F_Mask.svg
yardbird-B_Mask.svg
serving at port 9092
127.0.0.1 - - [27/May/2020 01:49:39] "GET /web/index.html HTTP/1.1" 200 -
127.0.0.1 - - [27/May/2020 01:49:39] "GET /web/style.css HTTP/1.1" 200 -
127.0.0.1 - - [27/May/2020 01:49:39] "GET /e80aa7/yardbird-B_Adhes.svg HTTP/1.1" 200 -
127.0.0.1 - - [27/May/2020 01:49:39] "GET /e80aa7/yardbird-B_Paste.svg HTTP/1.1" 200 -
127.0.0.1 - - [27/May/2020 01:49:39] "GET /e80aa7/yardbird-Edge_Cuts.svg HTTP/1.1" 200 -
127.0.0.1 - - [27/May/2020 01:49:39] "GET /e80aa7/yardbird-In1_Cu.svg HTTP/1.1" 200 -
127.0.0.1 - - [27/May/2020 01:49:39] "GET /e80aa7/yardbird-F_Paste.svg HTTP/1.1" 200 -
127.0.0.1 - - [27/May/2020 01:49:39] "GET /e80aa7/yardbird-Eco2_User.svg HTTP/1.1" 200 -
127.0.0.1 - - [27/May/2020 01:49:39] "GET /e80aa7/yardbird-F_Adhes.svg HTTP/1.1" 200 -
127.0.0.1 - - [27/May/2020 01:49:39] "GET /e80aa7/yardbird-Margin.svg HTTP/1.1" 200 -
127.0.0.1 - - [27/May/2020 01:49:39] "GET /e80aa7/yardbird-F_CrtYd.svg HTTP/1.1" 200 -
127.0.0.1 - - [27/May/2020 01:49:39] "GET /e80aa7/yardbird-F_SilkS.svg HTTP/1.1" 200 -
127.0.0.1 - - [27/May/2020 01:49:39] "GET /e80aa7/yardbird-F_Fab.svg HTTP/1.1" 200 -
127.0.0.1 - - [27/May/2020 01:49:39] "GET /e80aa7/yardbird-B_Cu.svg HTTP/1.1" 200 -
127.0.0.1 - - [27/May/2020 01:49:39] "GET /e80aa7/yardbird-Dwgs_User.svg HTTP/1.1" 200 -
127.0.0.1 - - [27/May/2020 01:49:39] "GET /e80aa7/yardbird-F_Cu.svg HTTP/1.1" 200 -
127.0.0.1 - - [27/May/2020 01:49:39] "GET /e80aa7/yardbird-In2_Cu.svg HTTP/1.1" 200 -
127.0.0.1 - - [27/May/2020 01:49:39] "GET /e80aa7/yardbird-B_Fab.svg HTTP/1.1" 200 -
127.0.0.1 - - [27/May/2020 01:49:39] "GET /e80aa7/yardbird-B_CrtYd.svg HTTP/1.1" 200 -
127.0.0.1 - - [27/May/2020 01:49:39] "GET /e80aa7/yardbird-Eco1_User.svg HTTP/1.1" 200 -
127.0.0.1 - - [27/May/2020 01:49:39] "GET /e80aa7/yardbird-Cmts_User.svg HTTP/1.1" 200 -
127.0.0.1 - - [27/May/2020 01:49:39] "GET /e80aa7/yardbird-B_SilkS.svg HTTP/1.1" 200 -
127.0.0.1 - - [27/May/2020 01:49:39] "GET /e80aa7/yardbird-F_Mask.svg HTTP/1.1" 200 -
127.0.0.1 - - [27/May/2020 01:49:39] "GET /e80aa7/yardbird-B_Mask.svg HTTP/1.1" 200 -
127.0.0.1 - - [27/May/2020 01:49:40] code 404, message File not found
127.0.0.1 - - [27/May/2020 01:49:40] "GET /favicon.ico HTTP/1.1" 404 -

**Comment by leoheck** [comment]
Ok, I have to study a pcb now.
But, let me help you with the command line. It is not good the way it is right now.
I will make some suggestions, and maybe a pr if you like this.

**Comment by leoheck** [comment]
Thank you for your help dude, it was awesome.
Let me ask one more question. Everything colored here is something that has changed?

![image](https://user-images.githubusercontent.com/1277920/82979160-bf472400-9fbc-11ea-93d1-4c4cf67f8385.png)

**Comment by leoheck** [comment]
Ah, we can definitely improve the tools path too. I will think about something to suggest too.

**Comment by sunwukonga** [comment]
Changes are highlighted red usually.

**Comment by leoheck** [comment]
Yeah, I figured out that I can click in the squares. Pretty nice! Really good stuff.

**Comment by leoheck** [comment]
Well, have a good night/day, here is late 2Am
