### ISSUE TITLE
Multiples projects in one Repo

### ISSUE THREAD

**Issue by leoheck** [Gasman2014/KiCad-Diff#19]
I have one repo with multiples Kicad projects and it looks like Kicad-diff is getting the wrong board for any reason, even when I pass the right one. 

Can this tool work with multiples projects like this? If not, do you think it is possible to fix it easely? 

I am going to investigate this myself but if you have any input to help me with that I appreciate to know.

For instance, this is my organization
```
myrepo
├── board-1
├── board-2
├── board-3
└── board-4
```

**Comment by Gasman2014** [comment]
Closed via [b1653f9]
