### ISSUE TITLE
Title, date and company are missing.

### ISSUE THREAD

**Issue by leoheck** [Gasman2014/KiCad-Diff#28]
I could not see title, date and company any more. Maybe something has changed with kicad 5.1.6

**Comment by Gasman2014** [comment]
Title, date and company are from the page setup in pcbnew. Doesn’t get picked up from eeschema as far as I can tell.  Just checked and working on the last commit on my master branch. 
Will have to see how this works on 5.99 - I know that the newer version supports path/name substitution. 

John Pateman

**Comment by leoheck** [comment]
Alright, for some reason they are not working on my sample projects
