### ISSUE TITLE
Does this produce diffs for schematic files?

### ISSUE THREAD

**Issue by shrub77** [Gasman2014/KiCad-Diff#3]
I see this tool is helpful for viewing diffs for pcb layouts,

does it also work with .sch files?

**Comment by jnavila** [comment]
In facts, that's the opposite: this tools allows viewing diffs in sch files, not pcb files.

**Comment by Gasman2014** [comment]
This application only produces diffs of pcbnew (*.kicad_pcb) layout files and not between schematics. Please see screenshots. You might like to look at jnavila’s repo on github - plotkicadsch and plotgitsch if you are looking for schematic diffs - https://github.com/jnavila/plotkicadsch

**Comment by Gasman2014** [comment]
Closed with redirection to another project that addresses schematic diffing.
