### ISSUE TITLE
grep dependency causes silent/inaccurate failure on Windows machines

### ISSUE THREAD

**Issue by Cushychicken** [Gasman2014/KiCad-Diff#31]
I downloaded and ran KiCad-Diff for the first time today, and could not get it to produce a diff of any two PCB files - even ones I knew were radically different. Then I noticed this line:

![image](https://user-images.githubusercontent.com/3886137/107370074-84384280-6ab0-11eb-96e0-d16634cbae5d.png)

Is there some way to remove the `grep` dependency here that will allow this to run smoothly on Windows 10? Or, perhaps, there's another way to run it that won't butt into this issue?

**Comment by Gasman2014** [comment]
It may be possible to use FINDSTR in Windows. I will have a look at some point - there may also be a different way to do this altogether. There is a bit of refactoring & development going on at present and this may get shaken out in the process.
I will keep this issue open.

**Comment by jnavila** [comment]
I'm working on putting all post processing of the scm commands in Python and remove reliance on external utilities. This way, the system is easier to run across platforms;

**Comment by jnavila** [comment]
@Cushychicken could you test with the latest version and report?

**Comment by Cushychicken** [comment]
@jnavila sure! May not be until the weekend.

Thanks for looking into this.

**Comment by leoheck** [comment]
meanwhile @Cushychicken if the grep command is missing you could use Windows PowerShell or the Linux subsystem for windows.

> I'm working on putting all post-processing of the same commands in Python and remove reliance on external utilities. 
@jnavila this would be nice!

**Comment by leoheck** [comment]
@jnavila did you solve this issue? If yes we could close this. What do you think?

**Comment by jnavila** [comment]
I did it in #34 and following. This can be closed.

**Comment by leoheck** [comment]
Oh, I cannot close it. maybe @Cushychicken or @Gasman2014

**Comment by Cushychicken** [comment]
Finally got around to testing - life has been insane these last few months

Fixed - closing

**Comment by leoheck** [comment]
@Cushychicken glad to hear that, thanks.
