### ISSUE TITLE
variable assigned but no use?

### ISSUE THREAD

**Issue by jnavila** [Gasman2014/KiCad-Diff#33]
https://github.com/Gasman2014/KiCad-Diff/blob/ba7a2228827586b339fe82112ffa19723a50d6e0/scms/svn.py#L39-L43

`prj_path` is assigned, there's even a comment, but it is not used after. Is it still useful?

**Comment by Gasman2014** [comment]
I think this was related to some work on sub-projects in a repo but I am not sure. Its probably harmless and there are worse things in the project!

**Comment by jnavila** [comment]
OK. I remove it. Thanks.
