### ISSUE TITLE
Feature Request - Buttons to iterate through the next/previous layers on in the Triptych view

### ISSUE THREAD

**Issue by leoheck** [Gasman2014/KiCad-Diff#38]
Hey @Gasman2014 how easy would be to improve the triptych view by adding 2 buttons to go to the next/previous comparison/layer? This would be a good improvement for the one that is actually reviewing things.

Also, how easy would be to adjust the html to make it autofit the browser. Right now the page is by default bigger than the window.

**Comment by Gasman2014** [comment]
I think what is needed first is to retrieve the actual layer names and iterate through these. At present, the stackup is fixed (and even included non-existent layers).

**Comment by leoheck** [comment]
Agree, and also, this seems to be easy.

One issue we are going to see doing this is the possibility of changes in the stack up.

For instance, the board starting with 2 layers and ending with 4 layers, and vice versa.
In this case, we need to generate a blank SVG to compare, or just to paint the whole SVG in a different color indicating it was added or removed.

**Comment by leoheck** [comment]
I am closing this right now.
