### ISSUE TITLE
Python dependencies

### ISSUE THREAD

**Issue by leoheck** [Gasman2014/KiCad-Diff#46]
This is a note to me to add python dependencies in the README.md and a requirements.txt or a setup.py or something to assist in installing dependencies.

**Comment by leoheck** [comment]
https://github.com/Gasman2014/KiCad-Diff/pull/47

**Comment by leoheck** [comment]
@Gasman2014 could you please accept this https://github.com/Gasman2014/KiCad-Diff/pull/47 pull request?
It adds a file that pip uses to track python dependencies. 

To use this file, it is just a matter of doing:
```bash 
pip install requirements.txt
```

**Comment by leoheck** [comment]
After that, we can also close this issue.

**Comment by Gasman2014** [comment]
Closed by 78f2d5c and a7e811
