### ISSUE TITLE
Y shift between commits

### ISSUE THREAD

**Issue by metropt** [Gasman2014/KiCad-Diff#49]
Hi,
KiCad-Diff is showing a Y shift however if I check x,y positions of the footpirnts between the two commits they are the same.

![image](https://user-images.githubusercontent.com/764040/112473660-89063c80-8d66-11eb-9dca-d5041da7e32f.png)

The only real difference between this two commits are these pads:
![image](https://user-images.githubusercontent.com/764040/112473704-991e1c00-8d66-11eb-93e2-b3283b4c27cc.png)

Any idea why this is happen?

**Comment by Gasman2014** [comment]
The current plotting logic depends on the bounding box for the entire design. If items, perhaps on another layer have moved or been added, then the whole plot is shifted. Check your other layers - perhaps something has been altered on the Dwgs or ECO layers?

**Comment by leoheck** [comment]
Yeap, true. We could check if it is possible to export the whole page instead. This could fix these minor issues.  And it makes sense since we have a lot of layers to pass through and check for changes.

**Comment by leoheck** [comment]
Oh, I found this, and also tested it. Doesn't work yet. Maybe it has to be used with another thing. 

> Do not try to change SetPlotFrameRef(False) to SetPlotFrameRef(true) the result is the pcbnew lib will crash if you try to plot the unknown frame references template.

**Comment by leoheck** [comment]
Hello @metropt, could you check if this issue can be closed? If so, feel free to close it, please.
