### ISSUE TITLE
What license are you releasing this software under?

### ISSUE THREAD

**Issue by jtzemp** [Gasman2014/KiCad-Diff#52]
Hey, @Gasman2014. Thanks for making this tool and making it available! I'd like to make a Docker image that includes your tool to make it easier for folks to use, but I'm not sure how you've licensed KiCad-Diff. I'd like to open-source my work as well and would make it clear that I was just packaging your project up to make it super easy to use.

Would you mind adding a license to your repo to make it clear for me and other folks how you'd like your software used?

If you'd like a site that helps you pick a license, check out https://choosealicense.com/. It was developed by Github and is pretty helpful.

If you don't care, you could always choose [MIT](https://choosealicense.com/licenses/mit/#suggest-this-license) as a default.

Thanks!

**Comment by Gasman2014** [comment]
I have added an MIT License. 

Adding a Docker image is a good plan. Thanks for your interest in this project
