### ISSUE TITLE
Tkinter GUI is black (macOS)

### ISSUE THREAD

**Issue by leoheck** [Gasman2014/KiCad-Diff#76]
Any idea on how to fix this issue, easily, for everyone?

<img width="813" alt="Screen Shot 2022-01-16 at 13 51 27" src="https://user-images.githubusercontent.com/1277920/149669543-edc8b78d-4ae9-4c89-b00e-52ac5464f50d.png">

**Comment by leoheck** [comment]
I saw this. But I could just find this solution
![image](https://user-images.githubusercontent.com/1277920/149795741-3d0ecdde-5f7a-43c3-9753-ba03a1d3171e.png)

Which involves in replacing the current python. My python on Monterey is 8.9.6 if I am not mistaken. I am not a macOS user, I believe this is not a good solution. But if you are fine with this solution I will try to apply it to check how it is going to work.

**Comment by Gasman2014** [comment]
I’m not sure its a good solution either!! In fact, It sounds like a fairly bad solution!

TBH. I wonder if it might be better long-term to use wx? After all, that’s what KiCad uses. I chose TKInter to begin with as it seemed a bit easier to use - for a very minimal interface. I have no experience with wx.

**Comment by leoheck** [comment]
Ok, if we find a designer tool, to help create wx interfaces we could copy the current one.
To be honest I also have no experience with GUI either haha

**Comment by leoheck** [comment]
Initial test using wxWidgets https://github.com/Gasman2014/KiCad-Diff/pull/78
